import Head from 'next/head'
import {
  Header,
  Hero,
  AddedRecently,
  TemperosAlhoeSal,
  TemperosSeco,
  Footer
} from '../components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className=''>
        <Header />
        <Hero />
        <AddedRecently />
        <TemperosAlhoeSal />
        <TemperosSeco />
        <Footer />
      </div>
    </div>
  )
}
