import Head from 'next/head'
import {
  Hero,
  AddedRecently,
  TemperosAlhoeSal,
  TemperosSeco,
} from '../components'

export default function Home() {
  return (
    <div className="px-8 sm:px-0 ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Hero />
        <AddedRecently />
        <TemperosAlhoeSal />
        <TemperosSeco />
      </div>
    </div>
  )
}
