import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/style";
import Image from "next/image";
import { imageUrlBuilder, sanity } from "../lib/sanity";

const query = `
*[_type == 'receitas'] { title, receitaDesc, receitaImage}
`;

const receitas = () => {
  const [receitas, setReceitas] = useState(null);

  useEffect(() => {
    sanity
      .fetch(query)
      .then((data) => setReceitas(data))
      .catch(console.error);
  }, []);

  if (!receitas) {
    return <h1>Loading…</h1>;
  }

  return (
    <section className={`${styles.section} flex-col px-4 sm:px-0 mt-6 :mt-10`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex font-poppins font-bold text-2xl sm:text-6xl">
        <h1 className="">Receitas</h1>
      </div>

      <div>
        <h2 className="font-poppins font-medium text-grey sm:mt-2 text-[12px] sm:text-sm">
          Ideias de receitas que você pode fazer usando Temperos Sabor e Sal.
          Não há limites para o seu uso.
        </h2>
      </div>
      {receitas.map(({ title, receitaDesc, receitaImage }) => (
        <div key={title} className="flex flex-col sm:flex-row">
          <div className="bg-[#ECECEC] rounded-lg p-4">
            <div className="relative">
              <Image className="rounded-lg"
                width="600px"
                height={450}
                layout="intrinsic"
                src={imageUrlBuilder.image(receitaImage).url()}
                alt={title}
              />
            </div>
            <div>
              <div>
                <h1 className="font-poppins font-semibol text-base">receita</h1>
              </div>
              <div>
                <p className="font-poppins text-[12px]">{receitaDesc}</p>
              </div>
              <div>Ler mais</div>
            </div>
          </div>
        </div>
      ))}
    </section>
  );
};

export default receitas;
