import React from "react";
import Head from "next/head";
import styles from "../styles/style";
import Image from "next/image";

const receitas = () => {
  return (
    <content className={`${styles.section} flex-col px-4 sm:px-0 mt-6 :mt-10`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex font-poppins font-bold text-2xl sm:text-6xl">
        <h1 className="">Receitas</h1>
      </div>

        <div>
          <h2 className="font-poppins font-medium text-grey sm:mt-2 text-[12px] sm:text-sm">
            Ideias de receitas que você pode fazer usando Temperos Sabor e Sal.
            Não há limites para o seu uso.
          </h2>
        </div>
        <div className="flex flex-col sm:flex-row">
          <div className="bg-[#ECECEC] rounded-lg p-4">
            <div>
              <Image />
            </div>
            <div>
              <div>
                <h1 className="font-poppins font-semibol text-base">
                  Titulo da Receita
                </h1>
              </div>
              <div>
                <p className="font-poppins text-[12px]">descrição</p>
              </div>
              <div>Ler mais</div>
            </div>
          </div>
        </div>
    </content>
  );
};

export default receitas;
