import Head from "next/head";
import React from "react";
import { temperos } from "../constants";
import Image from "next/image";
import styles from "../styles/style";
import {BsCart4} from 'react-icons/bs'

const temperosArtesanais = () => {
  return (
    <content className={`${styles.section} flex-col px-4 sm:px-0 mt-6 :mt-10`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex font-poppins font-bold sm:text-2xl">
        <h1 className="">Temperos Secos </h1>
        <h1 className="text-grey">{" ("}{temperos.length}{")"}</h1>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-4 mt-4">
        {temperos.map((nav, index) => (
          <div key={index} className="border-2 border-solid p-2 sm:p-4 max-w-[300px] rounded-xl shadow-sm">
            <div className="bg-[#ECECEC] rounded-xl">
              <Image src={nav.img} alt={nav.title} />
            </div>
            <div className="flex-col justify-between">
            <div className="font-poppins font-semibold text-[12px] sm:text-base mb-1 mt-2 sm:mt-3">
              <h2>{nav.title}</h2>
            </div>
            <div className="font-inter font-semibold text-sm text-[#ececec] flex justify-end">
              <p>{nav.peso}</p>
            </div>
            <div className="font-poppins text-[11px] sm:text-[12px] text-right mt-1">
              <p>{nav.description}</p>
            </div>
            </div>

            <div className="flex justify-between p-2 items-center">
              <div className="font-poppins font-semibold text-[14px] sm:text-xl flex justify-center">
                <p>R$ {nav.preco}</p>
              </div>
              <div className="bg-orange rounded-full text-white p-3"><BsCart4 className="fill-white h-4 w-4 sm:h-6 sm:w-6"/></div>
            </div>
          </div>
        ))}
      </div>
    </content>
  );
};

export default temperosArtesanais;
